services:
  postgres:
    image: postgres:15
    container_name: desafio-votacao-postgres
    environment:
      POSTGRES_DB: desafio_votacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - desafio-votacao-network

volumes:
  postgres_data:

networks:
  desafio-votacao-network:
    driver: bridge 